runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  
  
libraries:
  - name: ssl
    version: latest


#This section was added to try to reduce instances, this may not be needed
#The entire program was working both with and without this    
instance_class: F1
automatic_scaling:
  max_idle_instances: 1  # default value
  min_pending_latency: automatic  # default value
  max_pending_latency: 30ms

